[package]
name = "lasergraph-dsp-timecode-importer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.2"
clap = { version = "4.1.8", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
regex = "1"
